// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [`CreateDatasetConfig`][google.cloud.storageinsights.v1.StorageInsights.CreateDatasetConfig]
///
/// [google.cloud.storageinsights.v1.StorageInsights.CreateDatasetConfig]: <doc:StorageInsightsClient/createDatasetConfig(request:)>
public struct CreateDatasetConfigRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Value for parent.
  public var parent: Swift.String = Swift.String()

  /// Required. ID of the requesting object.
  /// If auto-generating ID is enabled on the server-side, remove this field and
  /// `dataset_config_id` from the method_signature of Create RPC
  /// Note: The value should not contain any hyphens.
  public var datasetConfigId: Swift.String = Swift.String()

  /// Required. The resource being created
  public var datasetConfig: DatasetConfig? = nil

  /// Optional. A unique identifier for your request.
  /// Specify the request ID if you need to retry the request.
  /// If you retry the request with the same ID within 60 minutes, the server
  /// ignores the request if it has already completed the original request.
  ///
  /// For example, if your initial request times out and you retry the request
  /// using the same request ID, the server recognizes the original request and
  /// does not process the new request.
  ///
  /// The request ID must be a valid UUID and cannot be a zero UUID
  /// (00000000-0000-0000-0000-000000000000).
  public var requestId: Swift.String = Swift.String()

  /// Initialize a new instance of `CreateDatasetConfigRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateDatasetConfigRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.storageinsights.v1.CreateDatasetConfigRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
