// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleRpc
import GoogleType

/// Message describing ReportDetail object. ReportDetail represents metadata of
/// generated reports for a ReportConfig.
/// Next ID: 10
public struct ReportDetail: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Name of resource. It will be of form
  /// projects/<project>/locations/<location>/reportConfigs/<report-config-id>/reportDetails/<report-detail-id>.
  public var name: Swift.String = Swift.String()

  /// The snapshot time.
  /// All the report data is referenced at this point of time.
  public var snapshotTime: GoogleCloudWkt.Timestamp? = nil

  /// Prefix of the object name of each report's shard. This will have full
  /// prefix except the "extension" and "shard_id".
  /// For example, if the `destination_path` is
  /// `{{report-config-id}}/dt={{datetime}}`, the shard object name would be
  /// `gs://my-insights/1A34-F2E456-12B456-1C3D/dt=2022-05-20T06:35/1A34-F2E456-12B456-1C3D_2022-05-20T06:35_5.csv`
  /// and the value of `report_path_prefix` field would be
  /// `gs://my-insights/1A34-F2E456-12B456-1C3D/dt=2022-05-20T06:35/1A34-F2E456-12B456-1C3D_2022-05-20T06:35_`.
  public var reportPathPrefix: Swift.String = Swift.String()

  /// Total shards generated for the report.
  public var shardsCount: Swift.Int64 = Swift.Int64()

  /// Status of the ReportDetail.
  public var status: GoogleRpc.Status? = nil

  /// Labels as key value pairs
  public var labels: [Swift.String: Swift.String] = [:]

  /// The date for which report is generated. The time part of target_datetime
  /// will be zero till we support multiple reports per day.
  public var targetDatetime: GoogleType.DateTime? = nil

  /// Metrics of the report.
  public var reportMetrics: ReportDetail.Metrics? = nil

  /// Initialize a new instance of `ReportDetail`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReportDetail().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Different metrics associated with the generated report.
  public struct Metrics: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Count of Cloud Storage objects which are part of the report.
    public var processedRecordsCount: Swift.Int64 = Swift.Int64()

    /// Initialize a new instance of `Metrics`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Metrics().with { $0.processedRecordsCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.storageinsights.v1.ReportDetail.Metrics"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.storageinsights.v1.ReportDetail"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
