// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Message describing ReportConfig object. ReportConfig is the configuration to
/// generate reports.
/// See
/// https://cloud.google.com/storage/docs/insights/using-inventory-reports#create-config-rest
/// for more details on how to set various fields.
/// Next ID: 12
public struct ReportConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// name of resource. It will be of form
  /// projects/<project>/locations/<location>/reportConfigs/<report-config-id>.
  public var name: Swift.String = Swift.String()

  /// Output only. [Output only] Create time stamp
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. [Output only] Update time stamp
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// The frequency of report generation.
  public var frequencyOptions: FrequencyOptions? = nil

  /// Labels as key value pairs
  public var labels: [Swift.String: Swift.String] = [:]

  /// User provided display name which can be empty and limited to 256 characters
  /// that is editable.
  public var displayName: Swift.String = Swift.String()

  /// Format in which report will be published.
  public var reportFormat: OneOf_ReportFormat? = nil

  /// Configuration options for report contents.
  public var reportKind: OneOf_ReportKind? = nil

  /// Initialize a new instance of `ReportConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReportConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: String, CodingKey {
    case name = "name"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case frequencyOptions = "frequencyOptions"
    case csvOptions = "csvOptions"
    case parquetOptions = "parquetOptions"
    case objectMetadataReportOptions = "objectMetadataReportOptions"
    case labels = "labels"
    case displayName = "displayName"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .updateTime)
    self.frequencyOptions = try container.decodeIfPresent(
      FrequencyOptions.self, forKey: .frequencyOptions)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.displayName = try container.decode(Swift.String.self, forKey: .displayName)

    var reportFormat: OneOf_ReportFormat? = nil
    let reportFormatCheckAndSet = {
      if reportFormat != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'reportFormat'"))
      }
      reportFormat = $0
    }
    if let csvOptions = try container.decodeIfPresent(CSVOptions?.self, forKey: .csvOptions) {
      try reportFormatCheckAndSet(.csvOptions(csvOptions))
    }
    if let parquetOptions = try container.decodeIfPresent(
      ParquetOptions?.self, forKey: .parquetOptions)
    {
      try reportFormatCheckAndSet(.parquetOptions(parquetOptions))
    }
    self.reportFormat = reportFormat

    var reportKind: OneOf_ReportKind? = nil
    let reportKindCheckAndSet = {
      if reportKind != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'reportKind'"))
      }
      reportKind = $0
    }
    if let objectMetadataReportOptions = try container.decodeIfPresent(
      ObjectMetadataReportOptions?.self, forKey: .objectMetadataReportOptions)
    {
      try reportKindCheckAndSet(.objectMetadataReportOptions(objectMetadataReportOptions))
    }
    self.reportKind = reportKind
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.frequencyOptions, forKey: .frequencyOptions)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.displayName, forKey: .displayName)

    if let choice = self.reportFormat {
      switch choice {
      case .csvOptions(let value):
        try container.encode(value, forKey: .csvOptions)
      case .parquetOptions(let value):
        try container.encode(value, forKey: .parquetOptions)
      }
    }

    if let choice = self.reportKind {
      switch choice {
      case .objectMetadataReportOptions(let value):
        try container.encode(value, forKey: .objectMetadataReportOptions)
      }
    }
  }

  /// Format in which report will be published.
  public enum OneOf_ReportFormat: Codable, Equatable, Sendable {
    /// Options for CSV formatted reports.
    indirect case csvOptions(CSVOptions?)
    /// Options for Parquet formatted reports.
    indirect case parquetOptions(ParquetOptions?)
  }

  /// Configuration options for report contents.
  public enum OneOf_ReportKind: Codable, Equatable, Sendable {
    /// Report for exporting object metadata.
    indirect case objectMetadataReportOptions(ObjectMetadataReportOptions?)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.storageinsights.v1.ReportConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
