// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Service describing handlers for resources
///
/// @Snippet(path: "StorageInsightsQuickstart")
public class StorageInsightsClient: Clients.StorageInsightsProtocol {
  let inner: any Clients.StorageInsightsStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `StorageInsightsClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.StorageInsightsStub = try Clients.StorageInsightsTransport(options)
    inner = Clients.StorageInsightsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.StorageInsightsLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists ReportConfigs in a given project and location.
  ///
  /// @Snippet(path: "StorageInsights_ListReportConfigs")
  public func listReportConfigs(
    request: ListReportConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ListReportConfigsResponse {
    try await self.inner.listReportConfigs(request: request, options: options)
  }

  /// Lists ReportConfigs in a given project and location.
  ///
  /// @Snippet(path: "StorageInsights_ListReportConfigs")
  public func listReportConfigs(
    byItem: ListReportConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ReportConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudStorageInsightsV1.ListReportConfigsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listReportConfigs(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single ReportConfig.
  ///
  /// @Snippet(path: "StorageInsights_GetReportConfig")
  public func getReportConfig(
    request: GetReportConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig {
    try await self.inner.getReportConfig(request: request, options: options)
  }

  /// Creates a new ReportConfig in a given project and location.
  ///
  /// @Snippet(path: "StorageInsights_CreateReportConfig")
  public func createReportConfig(
    request: CreateReportConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig {
    try await self.inner.createReportConfig(request: request, options: options)
  }

  /// Updates the parameters of a single ReportConfig.
  ///
  /// @Snippet(path: "StorageInsights_UpdateReportConfig")
  public func updateReportConfig(
    request: UpdateReportConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig {
    try await self.inner.updateReportConfig(request: request, options: options)
  }

  /// Deletes a single ReportConfig.
  ///
  /// @Snippet(path: "StorageInsights_DeleteReportConfig")
  public func deleteReportConfig(
    request: DeleteReportConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteReportConfig(request: request, options: options)
  }

  /// Lists ReportDetails in a given project and location.
  ///
  /// @Snippet(path: "StorageInsights_ListReportDetails")
  public func listReportDetails(
    request: ListReportDetailsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ListReportDetailsResponse {
    try await self.inner.listReportDetails(request: request, options: options)
  }

  /// Lists ReportDetails in a given project and location.
  ///
  /// @Snippet(path: "StorageInsights_ListReportDetails")
  public func listReportDetails(
    byItem: ListReportDetailsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ReportDetail, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudStorageInsightsV1.ListReportDetailsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listReportDetails(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single ReportDetail.
  ///
  /// @Snippet(path: "StorageInsights_GetReportDetail")
  public func getReportDetail(
    request: GetReportDetailRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ReportDetail {
    try await self.inner.getReportDetail(request: request, options: options)
  }

  /// Lists the dataset configurations in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_ListDatasetConfigs")
  public func listDatasetConfigs(
    request: ListDatasetConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ListDatasetConfigsResponse {
    try await self.inner.listDatasetConfigs(request: request, options: options)
  }

  /// Lists the dataset configurations in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_ListDatasetConfigs")
  public func listDatasetConfigs(
    byItem: ListDatasetConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<DatasetConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudStorageInsightsV1.ListDatasetConfigsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listDatasetConfigs(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets the dataset configuration in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_GetDatasetConfig")
  public func getDatasetConfig(
    request: GetDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.DatasetConfig {
    try await self.inner.getDatasetConfig(request: request, options: options)
  }

  /// Creates a dataset configuration in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_CreateDatasetConfig")
  public func createDatasetConfig(
    request: CreateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createDatasetConfig(request: request, options: options)
  }

  /// Creates a dataset configuration in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_CreateDatasetConfig")
  public func createDatasetConfig(
    withPolling: CreateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<DatasetConfig> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<DatasetConfig>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try DatasetConfig(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createDatasetConfig(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<DatasetConfig>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates a dataset configuration in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_UpdateDatasetConfig")
  public func updateDatasetConfig(
    request: UpdateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateDatasetConfig(request: request, options: options)
  }

  /// Updates a dataset configuration in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_UpdateDatasetConfig")
  public func updateDatasetConfig(
    withPolling: UpdateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<DatasetConfig> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<DatasetConfig>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try DatasetConfig(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.updateDatasetConfig(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<DatasetConfig>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a dataset configuration in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_DeleteDatasetConfig")
  public func deleteDatasetConfig(
    request: DeleteDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteDatasetConfig(request: request, options: options)
  }

  /// Deletes a dataset configuration in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_DeleteDatasetConfig")
  public func deleteDatasetConfig(
    withPolling: DeleteDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteDatasetConfig(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Links a dataset to BigQuery in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_LinkDataset")
  public func linkDataset(
    request: LinkDatasetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.linkDataset(request: request, options: options)
  }

  /// Links a dataset to BigQuery in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_LinkDataset")
  public func linkDataset(
    withPolling: LinkDatasetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<LinkDatasetResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<LinkDatasetResponse>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try LinkDatasetResponse(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.linkDataset(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<LinkDatasetResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Unlinks a dataset from BigQuery in a given project
  /// for a given location.
  ///
  /// @Snippet(path: "StorageInsights_UnlinkDataset")
  public func unlinkDataset(
    request: UnlinkDatasetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.unlinkDataset(request: request, options: options)
  }

  /// Unlinks a dataset from BigQuery in a given project
  /// for a given location.
  ///
  /// @Snippet(path: "StorageInsights_UnlinkDataset")
  public func unlinkDataset(
    withPolling: UnlinkDatasetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.unlinkDataset(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "StorageInsights_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "StorageInsights_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "StorageInsights_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "StorageInsights_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "StorageInsights_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "StorageInsights_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "StorageInsights_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "StorageInsights_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `StorageInsightsClient`.
  ///
  /// To mock `StorageInsightsClient` change your functions to receive
  /// `some StorageInsightsProtocol` or `any StorageInsightsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol StorageInsightsProtocol {
    /// See `StorageInsightsClient.listReportConfigs`.
    func listReportConfigs(request: ListReportConfigsRequest) async throws
      -> GoogleCloudStorageInsightsV1.ListReportConfigsResponse

    /// See `StorageInsightsClient.listReportConfigs`.
    func listReportConfigs(
      byItem: ListReportConfigsRequest
    ) throws -> any AsyncSequence<ReportConfig, Swift.Error>

    /// See `StorageInsightsClient.listReportConfigs`.
    func listReportConfigs(
      parent: Swift.String,
    ) throws -> any AsyncSequence<ReportConfig, Swift.Error>

    /// See `StorageInsightsClient.getReportConfig`.
    func getReportConfig(request: GetReportConfigRequest) async throws
      -> GoogleCloudStorageInsightsV1.ReportConfig

    /// See `StorageInsightsClient.getReportConfig`.
    func getReportConfig(
      name: Swift.String,
    ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig

    /// See `StorageInsightsClient.createReportConfig`.
    func createReportConfig(request: CreateReportConfigRequest) async throws
      -> GoogleCloudStorageInsightsV1.ReportConfig

    /// See `StorageInsightsClient.createReportConfig`.
    func createReportConfig(
      parent: Swift.String,
      reportConfig: ReportConfig?,
    ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig

    /// See `StorageInsightsClient.updateReportConfig`.
    func updateReportConfig(request: UpdateReportConfigRequest) async throws
      -> GoogleCloudStorageInsightsV1.ReportConfig

    /// See `StorageInsightsClient.updateReportConfig`.
    func updateReportConfig(
      reportConfig: ReportConfig?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig

    /// See `StorageInsightsClient.deleteReportConfig`.
    func deleteReportConfig(request: DeleteReportConfigRequest) async throws

    /// See `StorageInsightsClient.deleteReportConfig`.
    func deleteReportConfig(
      name: Swift.String,
    ) async throws

    /// See `StorageInsightsClient.listReportDetails`.
    func listReportDetails(request: ListReportDetailsRequest) async throws
      -> GoogleCloudStorageInsightsV1.ListReportDetailsResponse

    /// See `StorageInsightsClient.listReportDetails`.
    func listReportDetails(
      byItem: ListReportDetailsRequest
    ) throws -> any AsyncSequence<ReportDetail, Swift.Error>

    /// See `StorageInsightsClient.listReportDetails`.
    func listReportDetails(
      parent: Swift.String,
    ) throws -> any AsyncSequence<ReportDetail, Swift.Error>

    /// See `StorageInsightsClient.getReportDetail`.
    func getReportDetail(request: GetReportDetailRequest) async throws
      -> GoogleCloudStorageInsightsV1.ReportDetail

    /// See `StorageInsightsClient.getReportDetail`.
    func getReportDetail(
      name: Swift.String,
    ) async throws -> GoogleCloudStorageInsightsV1.ReportDetail

    /// See `StorageInsightsClient.listDatasetConfigs`.
    func listDatasetConfigs(request: ListDatasetConfigsRequest) async throws
      -> GoogleCloudStorageInsightsV1.ListDatasetConfigsResponse

    /// See `StorageInsightsClient.listDatasetConfigs`.
    func listDatasetConfigs(
      byItem: ListDatasetConfigsRequest
    ) throws -> any AsyncSequence<DatasetConfig, Swift.Error>

    /// See `StorageInsightsClient.listDatasetConfigs`.
    func listDatasetConfigs(
      parent: Swift.String,
    ) throws -> any AsyncSequence<DatasetConfig, Swift.Error>

    /// See `StorageInsightsClient.getDatasetConfig`.
    func getDatasetConfig(request: GetDatasetConfigRequest) async throws
      -> GoogleCloudStorageInsightsV1.DatasetConfig

    /// See `StorageInsightsClient.getDatasetConfig`.
    func getDatasetConfig(
      name: Swift.String,
    ) async throws -> GoogleCloudStorageInsightsV1.DatasetConfig

    /// See `StorageInsightsClient.createDatasetConfig`.
    func createDatasetConfig(request: CreateDatasetConfigRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `StorageInsightsClient.createDatasetConfig`.
    func createDatasetConfig(withPolling: CreateDatasetConfigRequest) async throws
      -> any GoogleCloudGax.PollableOperation<DatasetConfig>

    /// See `StorageInsightsClient.createDatasetConfig`.
    func createDatasetConfig(
      parent: Swift.String,
      datasetConfig: DatasetConfig?,
      datasetConfigId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<DatasetConfig>

    /// See `StorageInsightsClient.updateDatasetConfig`.
    func updateDatasetConfig(request: UpdateDatasetConfigRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `StorageInsightsClient.updateDatasetConfig`.
    func updateDatasetConfig(withPolling: UpdateDatasetConfigRequest) async throws
      -> any GoogleCloudGax.PollableOperation<DatasetConfig>

    /// See `StorageInsightsClient.updateDatasetConfig`.
    func updateDatasetConfig(
      datasetConfig: DatasetConfig?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<DatasetConfig>

    /// See `StorageInsightsClient.deleteDatasetConfig`.
    func deleteDatasetConfig(request: DeleteDatasetConfigRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `StorageInsightsClient.deleteDatasetConfig`.
    func deleteDatasetConfig(withPolling: DeleteDatasetConfigRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Void>

    /// See `StorageInsightsClient.deleteDatasetConfig`.
    func deleteDatasetConfig(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `StorageInsightsClient.linkDataset`.
    func linkDataset(request: LinkDatasetRequest) async throws -> GoogleLongRunning.Operation

    /// See `StorageInsightsClient.linkDataset`.
    func linkDataset(withPolling: LinkDatasetRequest) async throws -> any GoogleCloudGax
      .PollableOperation<LinkDatasetResponse>

    /// See `StorageInsightsClient.linkDataset`.
    func linkDataset(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<LinkDatasetResponse>

    /// See `StorageInsightsClient.unlinkDataset`.
    func unlinkDataset(request: UnlinkDatasetRequest) async throws -> GoogleLongRunning.Operation

    /// See `StorageInsightsClient.unlinkDataset`.
    func unlinkDataset(withPolling: UnlinkDatasetRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Void>

    /// See `StorageInsightsClient.unlinkDataset`.
    func unlinkDataset(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `StorageInsightsClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `StorageInsightsClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `StorageInsightsClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `StorageInsightsClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `StorageInsightsClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `StorageInsightsClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `StorageInsightsClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `StorageInsightsClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `StorageInsightsClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `StorageInsightsClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `StorageInsightsClient.listReportConfigs`.
    func listReportConfigs(
      request: ListReportConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.ListReportConfigsResponse

    /// See `StorageInsightsClient.listReportConfigs`.
    func listReportConfigs(
      byItem: ListReportConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ReportConfig, Swift.Error>

    /// See `StorageInsightsClient.getReportConfig`.
    func getReportConfig(
      request: GetReportConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig

    /// See `StorageInsightsClient.createReportConfig`.
    func createReportConfig(
      request: CreateReportConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig

    /// See `StorageInsightsClient.updateReportConfig`.
    func updateReportConfig(
      request: UpdateReportConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig

    /// See `StorageInsightsClient.deleteReportConfig`.
    func deleteReportConfig(
      request: DeleteReportConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `StorageInsightsClient.listReportDetails`.
    func listReportDetails(
      request: ListReportDetailsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.ListReportDetailsResponse

    /// See `StorageInsightsClient.listReportDetails`.
    func listReportDetails(
      byItem: ListReportDetailsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ReportDetail, Swift.Error>

    /// See `StorageInsightsClient.getReportDetail`.
    func getReportDetail(
      request: GetReportDetailRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.ReportDetail

    /// See `StorageInsightsClient.listDatasetConfigs`.
    func listDatasetConfigs(
      request: ListDatasetConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.ListDatasetConfigsResponse

    /// See `StorageInsightsClient.listDatasetConfigs`.
    func listDatasetConfigs(
      byItem: ListDatasetConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<DatasetConfig, Swift.Error>

    /// See `StorageInsightsClient.getDatasetConfig`.
    func getDatasetConfig(
      request: GetDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.DatasetConfig

    /// See `StorageInsightsClient.createDatasetConfig`.
    func createDatasetConfig(
      request: CreateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `StorageInsightsClient.createDatasetConfig`.
    func createDatasetConfig(
      withPolling: CreateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<DatasetConfig>

    /// See `StorageInsightsClient.updateDatasetConfig`.
    func updateDatasetConfig(
      request: UpdateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `StorageInsightsClient.updateDatasetConfig`.
    func updateDatasetConfig(
      withPolling: UpdateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<DatasetConfig>

    /// See `StorageInsightsClient.deleteDatasetConfig`.
    func deleteDatasetConfig(
      request: DeleteDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `StorageInsightsClient.deleteDatasetConfig`.
    func deleteDatasetConfig(
      withPolling: DeleteDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `StorageInsightsClient.linkDataset`.
    func linkDataset(
      request: LinkDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `StorageInsightsClient.linkDataset`.
    func linkDataset(
      withPolling: LinkDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<LinkDatasetResponse>

    /// See `StorageInsightsClient.unlinkDataset`.
    func unlinkDataset(
      request: UnlinkDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `StorageInsightsClient.unlinkDataset`.
    func unlinkDataset(
      withPolling: UnlinkDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `StorageInsightsClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `StorageInsightsClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `StorageInsightsClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `StorageInsightsClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `StorageInsightsClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `StorageInsightsClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `StorageInsightsClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.StorageInsightsProtocol {
  public func listReportConfigs(request: ListReportConfigsRequest) async throws
    -> GoogleCloudStorageInsightsV1.ListReportConfigsResponse
  {
    try await self.listReportConfigs(request: request, options: .init())
  }

  public func listReportConfigs(
    request: ListReportConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ListReportConfigsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listReportConfigs(
    byItem: ListReportConfigsRequest
  ) throws -> any AsyncSequence<ReportConfig, Swift.Error> {
    try self.listReportConfigs(byItem: byItem, options: .init())
  }

  public func listReportConfigs(
    byItem: ListReportConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ReportConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudStorageInsightsV1.ListReportConfigsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listReportConfigs(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ReportConfig, Swift.Error> {
    let request = ListReportConfigsRequest().with {
      $0.parent = parent
    }
    return try self.listReportConfigs(byItem: request)
  }

  public func getReportConfig(request: GetReportConfigRequest) async throws
    -> GoogleCloudStorageInsightsV1.ReportConfig
  {
    try await self.getReportConfig(request: request, options: .init())
  }

  public func getReportConfig(
    request: GetReportConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getReportConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig {
    let request = GetReportConfigRequest().with {
      $0.name = name
    }
    return try await self.getReportConfig(request: request)
  }

  public func createReportConfig(request: CreateReportConfigRequest) async throws
    -> GoogleCloudStorageInsightsV1.ReportConfig
  {
    try await self.createReportConfig(request: request, options: .init())
  }

  public func createReportConfig(
    request: CreateReportConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createReportConfig(
    parent: Swift.String,
    reportConfig: ReportConfig?,
  ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig {
    let request = CreateReportConfigRequest().with {
      $0.parent = parent
      $0.reportConfig = reportConfig
    }
    return try await self.createReportConfig(request: request)
  }

  public func updateReportConfig(request: UpdateReportConfigRequest) async throws
    -> GoogleCloudStorageInsightsV1.ReportConfig
  {
    try await self.updateReportConfig(request: request, options: .init())
  }

  public func updateReportConfig(
    request: UpdateReportConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateReportConfig(
    reportConfig: ReportConfig?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig {
    let request = UpdateReportConfigRequest().with {
      $0.reportConfig = reportConfig
      $0.updateMask = updateMask
    }
    return try await self.updateReportConfig(request: request)
  }

  public func deleteReportConfig(request: DeleteReportConfigRequest) async throws {
    try await self.deleteReportConfig(request: request, options: .init())
  }

  public func deleteReportConfig(
    request: DeleteReportConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteReportConfig(
    name: Swift.String,
  ) async throws {
    let request = DeleteReportConfigRequest().with {
      $0.name = name
    }
    try await self.deleteReportConfig(request: request)
  }

  public func listReportDetails(request: ListReportDetailsRequest) async throws
    -> GoogleCloudStorageInsightsV1.ListReportDetailsResponse
  {
    try await self.listReportDetails(request: request, options: .init())
  }

  public func listReportDetails(
    request: ListReportDetailsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ListReportDetailsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listReportDetails(
    byItem: ListReportDetailsRequest
  ) throws -> any AsyncSequence<ReportDetail, Swift.Error> {
    try self.listReportDetails(byItem: byItem, options: .init())
  }

  public func listReportDetails(
    byItem: ListReportDetailsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ReportDetail, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudStorageInsightsV1.ListReportDetailsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listReportDetails(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ReportDetail, Swift.Error> {
    let request = ListReportDetailsRequest().with {
      $0.parent = parent
    }
    return try self.listReportDetails(byItem: request)
  }

  public func getReportDetail(request: GetReportDetailRequest) async throws
    -> GoogleCloudStorageInsightsV1.ReportDetail
  {
    try await self.getReportDetail(request: request, options: .init())
  }

  public func getReportDetail(
    request: GetReportDetailRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ReportDetail {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getReportDetail(
    name: Swift.String,
  ) async throws -> GoogleCloudStorageInsightsV1.ReportDetail {
    let request = GetReportDetailRequest().with {
      $0.name = name
    }
    return try await self.getReportDetail(request: request)
  }

  public func listDatasetConfigs(request: ListDatasetConfigsRequest) async throws
    -> GoogleCloudStorageInsightsV1.ListDatasetConfigsResponse
  {
    try await self.listDatasetConfigs(request: request, options: .init())
  }

  public func listDatasetConfigs(
    request: ListDatasetConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.ListDatasetConfigsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listDatasetConfigs(
    byItem: ListDatasetConfigsRequest
  ) throws -> any AsyncSequence<DatasetConfig, Swift.Error> {
    try self.listDatasetConfigs(byItem: byItem, options: .init())
  }

  public func listDatasetConfigs(
    byItem: ListDatasetConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<DatasetConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudStorageInsightsV1.ListDatasetConfigsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listDatasetConfigs(
    parent: Swift.String,
  ) throws -> any AsyncSequence<DatasetConfig, Swift.Error> {
    let request = ListDatasetConfigsRequest().with {
      $0.parent = parent
    }
    return try self.listDatasetConfigs(byItem: request)
  }

  public func getDatasetConfig(request: GetDatasetConfigRequest) async throws
    -> GoogleCloudStorageInsightsV1.DatasetConfig
  {
    try await self.getDatasetConfig(request: request, options: .init())
  }

  public func getDatasetConfig(
    request: GetDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageInsightsV1.DatasetConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getDatasetConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudStorageInsightsV1.DatasetConfig {
    let request = GetDatasetConfigRequest().with {
      $0.name = name
    }
    return try await self.getDatasetConfig(request: request)
  }

  public func createDatasetConfig(request: CreateDatasetConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createDatasetConfig(request: request, options: .init())
  }

  public func createDatasetConfig(
    request: CreateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createDatasetConfig(withPolling: CreateDatasetConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<DatasetConfig>
  {
    try await self.createDatasetConfig(withPolling: withPolling, options: .init())
  }

  public func createDatasetConfig(
    withPolling: CreateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<DatasetConfig> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<DatasetConfig>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createDatasetConfig(
    parent: Swift.String,
    datasetConfig: DatasetConfig?,
    datasetConfigId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<DatasetConfig> {
    let request = CreateDatasetConfigRequest().with {
      $0.parent = parent
      $0.datasetConfig = datasetConfig
      $0.datasetConfigId = datasetConfigId
    }
    return try await self.createDatasetConfig(withPolling: request)
  }

  public func updateDatasetConfig(request: UpdateDatasetConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateDatasetConfig(request: request, options: .init())
  }

  public func updateDatasetConfig(
    request: UpdateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateDatasetConfig(withPolling: UpdateDatasetConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<DatasetConfig>
  {
    try await self.updateDatasetConfig(withPolling: withPolling, options: .init())
  }

  public func updateDatasetConfig(
    withPolling: UpdateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<DatasetConfig> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<DatasetConfig>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateDatasetConfig(
    datasetConfig: DatasetConfig?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<DatasetConfig> {
    let request = UpdateDatasetConfigRequest().with {
      $0.datasetConfig = datasetConfig
      $0.updateMask = updateMask
    }
    return try await self.updateDatasetConfig(withPolling: request)
  }

  public func deleteDatasetConfig(request: DeleteDatasetConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteDatasetConfig(request: request, options: .init())
  }

  public func deleteDatasetConfig(
    request: DeleteDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteDatasetConfig(withPolling: DeleteDatasetConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Void>
  {
    try await self.deleteDatasetConfig(withPolling: withPolling, options: .init())
  }

  public func deleteDatasetConfig(
    withPolling: DeleteDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteDatasetConfig(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteDatasetConfigRequest().with {
      $0.name = name
    }
    return try await self.deleteDatasetConfig(withPolling: request)
  }

  public func linkDataset(request: LinkDatasetRequest) async throws -> GoogleLongRunning.Operation {
    try await self.linkDataset(request: request, options: .init())
  }

  public func linkDataset(
    request: LinkDatasetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func linkDataset(withPolling: LinkDatasetRequest) async throws -> any GoogleCloudGax
    .PollableOperation<LinkDatasetResponse>
  {
    try await self.linkDataset(withPolling: withPolling, options: .init())
  }

  public func linkDataset(
    withPolling: LinkDatasetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<LinkDatasetResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<LinkDatasetResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func linkDataset(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<LinkDatasetResponse> {
    let request = LinkDatasetRequest().with {
      $0.name = name
    }
    return try await self.linkDataset(withPolling: request)
  }

  public func unlinkDataset(request: UnlinkDatasetRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.unlinkDataset(request: request, options: .init())
  }

  public func unlinkDataset(
    request: UnlinkDatasetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func unlinkDataset(withPolling: UnlinkDatasetRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>
  {
    try await self.unlinkDataset(withPolling: withPolling, options: .init())
  }

  public func unlinkDataset(
    withPolling: UnlinkDatasetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func unlinkDataset(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = UnlinkDatasetRequest().with {
      $0.name = name
    }
    return try await self.unlinkDataset(withPolling: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
