// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class StorageInsightsLogging: StorageInsightsStub {
    let inner: any StorageInsightsStub
    let logger: Logger

    public init(_ inner: any StorageInsightsStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-storageinsights-v1"
      logger[metadataKey: "gcp.client.service"] = "storageinsights"
      logger[metadataKey: "gcp.experimental.swift.client"] = "StorageInsights"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listReportConfigs(
      request: ListReportConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageinsightsV1.ListReportConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listReportConfigs",
        action: {
          (r: ListReportConfigsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudStorageinsightsV1.ListReportConfigsResponse
          in
          return try await self.inner.listReportConfigs(request: r, options: o)
        })
    }

    public func getReportConfig(
      request: GetReportConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageinsightsV1.ReportConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getReportConfig",
        action: {
          (r: GetReportConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudStorageinsightsV1.ReportConfig
          in
          return try await self.inner.getReportConfig(request: r, options: o)
        })
    }

    public func createReportConfig(
      request: CreateReportConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageinsightsV1.ReportConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "createReportConfig",
        action: {
          (r: CreateReportConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudStorageinsightsV1.ReportConfig
          in
          return try await self.inner.createReportConfig(request: r, options: o)
        })
    }

    public func updateReportConfig(
      request: UpdateReportConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageinsightsV1.ReportConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateReportConfig",
        action: {
          (r: UpdateReportConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudStorageinsightsV1.ReportConfig
          in
          return try await self.inner.updateReportConfig(request: r, options: o)
        })
    }

    public func deleteReportConfig(
      request: DeleteReportConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteReportConfig",
        action: {
          (r: DeleteReportConfigRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteReportConfig(request: r, options: o)
        })
    }

    public func listReportDetails(
      request: ListReportDetailsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageinsightsV1.ListReportDetailsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listReportDetails",
        action: {
          (r: ListReportDetailsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudStorageinsightsV1.ListReportDetailsResponse
          in
          return try await self.inner.listReportDetails(request: r, options: o)
        })
    }

    public func getReportDetail(
      request: GetReportDetailRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageinsightsV1.ReportDetail {
      try await self._intercept(
        request: request,
        options: options,
        name: "getReportDetail",
        action: {
          (r: GetReportDetailRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudStorageinsightsV1.ReportDetail
          in
          return try await self.inner.getReportDetail(request: r, options: o)
        })
    }

    public func listDatasetConfigs(
      request: ListDatasetConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageinsightsV1.ListDatasetConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDatasetConfigs",
        action: {
          (r: ListDatasetConfigsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudStorageinsightsV1.ListDatasetConfigsResponse
          in
          return try await self.inner.listDatasetConfigs(request: r, options: o)
        })
    }

    public func getDatasetConfig(
      request: GetDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageinsightsV1.DatasetConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDatasetConfig",
        action: {
          (r: GetDatasetConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudStorageinsightsV1.DatasetConfig
          in
          return try await self.inner.getDatasetConfig(request: r, options: o)
        })
    }

    public func createDatasetConfig(
      request: CreateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createDatasetConfig",
        action: {
          (r: CreateDatasetConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.createDatasetConfig(request: r, options: o)
        })
    }

    public func updateDatasetConfig(
      request: UpdateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateDatasetConfig",
        action: {
          (r: UpdateDatasetConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.updateDatasetConfig(request: r, options: o)
        })
    }

    public func deleteDatasetConfig(
      request: DeleteDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteDatasetConfig",
        action: {
          (r: DeleteDatasetConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.deleteDatasetConfig(request: r, options: o)
        })
    }

    public func linkDataset(
      request: LinkDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "linkDataset",
        action: {
          (r: LinkDatasetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.linkDataset(request: r, options: o)
        })
    }

    public func unlinkDataset(
      request: UnlinkDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "unlinkDataset",
        action: {
          (r: UnlinkDatasetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.unlinkDataset(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongrunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongrunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongrunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongrunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongrunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
