// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol StorageInsightsStub: Sendable {
    func listReportConfigs(
      request: ListReportConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.ListReportConfigsResponse

    func getReportConfig(
      request: GetReportConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig

    func createReportConfig(
      request: CreateReportConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig

    func updateReportConfig(
      request: UpdateReportConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.ReportConfig

    func deleteReportConfig(
      request: DeleteReportConfigRequest, options: GoogleGax.RequestOptions
    ) async throws

    func listReportDetails(
      request: ListReportDetailsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.ListReportDetailsResponse

    func getReportDetail(
      request: GetReportDetailRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.ReportDetail

    func listDatasetConfigs(
      request: ListDatasetConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.ListDatasetConfigsResponse

    func getDatasetConfig(
      request: GetDatasetConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudStorageInsightsV1.DatasetConfig

    func createDatasetConfig(
      request: CreateDatasetConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateDatasetConfig(
      request: UpdateDatasetConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteDatasetConfig(
      request: DeleteDatasetConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func linkDataset(
      request: LinkDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func unlinkDataset(
      request: UnlinkDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
