// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

import GoogleCloudAuth
import GoogleCloudGax
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import Logging

/// Service describing handlers for resources
///
/// @Snippet(path: "StorageInsightsQuickstart")
public protocol StorageInsights {
  /// Lists ReportConfigs in a given project and location.
  ///
  /// @Snippet(path: "StorageInsights_ListReportConfigs")
  func listReportConfigs(request: ListReportConfigsRequest) async throws
    -> GoogleCloudStorageinsightsV1.ListReportConfigsResponse

  /// Lists ReportConfigs in a given project and location.
  func listReportConfigs(
    byItem: ListReportConfigsRequest
  ) throws -> any AsyncSequence<ReportConfig, Swift.Error>

  /// Lists ReportConfigs in a given project and location.
  func listReportConfigs(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ReportConfig, Swift.Error>

  /// Gets details of a single ReportConfig.
  ///
  /// @Snippet(path: "StorageInsights_GetReportConfig")
  func getReportConfig(request: GetReportConfigRequest) async throws
    -> GoogleCloudStorageinsightsV1.ReportConfig

  /// Gets details of a single ReportConfig.
  func getReportConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudStorageinsightsV1.ReportConfig

  /// Creates a new ReportConfig in a given project and location.
  ///
  /// @Snippet(path: "StorageInsights_CreateReportConfig")
  func createReportConfig(request: CreateReportConfigRequest) async throws
    -> GoogleCloudStorageinsightsV1.ReportConfig

  /// Creates a new ReportConfig in a given project and location.
  func createReportConfig(
    parent: Swift.String,
    reportConfig: ReportConfig?,
  ) async throws -> GoogleCloudStorageinsightsV1.ReportConfig

  /// Updates the parameters of a single ReportConfig.
  ///
  /// @Snippet(path: "StorageInsights_UpdateReportConfig")
  func updateReportConfig(request: UpdateReportConfigRequest) async throws
    -> GoogleCloudStorageinsightsV1.ReportConfig

  /// Updates the parameters of a single ReportConfig.
  func updateReportConfig(
    reportConfig: ReportConfig?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleCloudStorageinsightsV1.ReportConfig

  /// Deletes a single ReportConfig.
  ///
  /// @Snippet(path: "StorageInsights_DeleteReportConfig")
  func deleteReportConfig(request: DeleteReportConfigRequest) async throws

  /// Deletes a single ReportConfig.
  func deleteReportConfig(
    name: Swift.String,
  ) async throws

  /// Lists ReportDetails in a given project and location.
  ///
  /// @Snippet(path: "StorageInsights_ListReportDetails")
  func listReportDetails(request: ListReportDetailsRequest) async throws
    -> GoogleCloudStorageinsightsV1.ListReportDetailsResponse

  /// Lists ReportDetails in a given project and location.
  func listReportDetails(
    byItem: ListReportDetailsRequest
  ) throws -> any AsyncSequence<ReportDetail, Swift.Error>

  /// Lists ReportDetails in a given project and location.
  func listReportDetails(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ReportDetail, Swift.Error>

  /// Gets details of a single ReportDetail.
  ///
  /// @Snippet(path: "StorageInsights_GetReportDetail")
  func getReportDetail(request: GetReportDetailRequest) async throws
    -> GoogleCloudStorageinsightsV1.ReportDetail

  /// Gets details of a single ReportDetail.
  func getReportDetail(
    name: Swift.String,
  ) async throws -> GoogleCloudStorageinsightsV1.ReportDetail

  /// Lists the dataset configurations in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_ListDatasetConfigs")
  func listDatasetConfigs(request: ListDatasetConfigsRequest) async throws
    -> GoogleCloudStorageinsightsV1.ListDatasetConfigsResponse

  /// Lists the dataset configurations in a given project for a given location.
  func listDatasetConfigs(
    byItem: ListDatasetConfigsRequest
  ) throws -> any AsyncSequence<DatasetConfig, Swift.Error>

  /// Lists the dataset configurations in a given project for a given location.
  func listDatasetConfigs(
    parent: Swift.String,
  ) throws -> any AsyncSequence<DatasetConfig, Swift.Error>

  /// Gets the dataset configuration in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_GetDatasetConfig")
  func getDatasetConfig(request: GetDatasetConfigRequest) async throws
    -> GoogleCloudStorageinsightsV1.DatasetConfig

  /// Gets the dataset configuration in a given project for a given location.
  func getDatasetConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudStorageinsightsV1.DatasetConfig

  /// Creates a dataset configuration in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_CreateDatasetConfig")
  func createDatasetConfig(request: CreateDatasetConfigRequest) async throws
    -> GoogleLongrunning.Operation

  /// Creates a dataset configuration in a given project for a given location.
  func createDatasetConfig(withPolling: CreateDatasetConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<DatasetConfig>

  /// Creates a dataset configuration in a given project for a given location.
  func createDatasetConfig(
    parent: Swift.String,
    datasetConfig: DatasetConfig?,
    datasetConfigId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<DatasetConfig>

  /// Updates a dataset configuration in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_UpdateDatasetConfig")
  func updateDatasetConfig(request: UpdateDatasetConfigRequest) async throws
    -> GoogleLongrunning.Operation

  /// Updates a dataset configuration in a given project for a given location.
  func updateDatasetConfig(withPolling: UpdateDatasetConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<DatasetConfig>

  /// Updates a dataset configuration in a given project for a given location.
  func updateDatasetConfig(
    datasetConfig: DatasetConfig?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<DatasetConfig>

  /// Deletes a dataset configuration in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_DeleteDatasetConfig")
  func deleteDatasetConfig(request: DeleteDatasetConfigRequest) async throws
    -> GoogleLongrunning.Operation

  /// Deletes a dataset configuration in a given project for a given location.
  func deleteDatasetConfig(withPolling: DeleteDatasetConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Void>

  /// Deletes a dataset configuration in a given project for a given location.
  func deleteDatasetConfig(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void>

  /// Links a dataset to BigQuery in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_LinkDataset")
  func linkDataset(request: LinkDatasetRequest) async throws -> GoogleLongrunning.Operation

  /// Links a dataset to BigQuery in a given project for a given location.
  func linkDataset(withPolling: LinkDatasetRequest) async throws -> any GoogleCloudGax
    .PollableOperation<LinkDatasetResponse>

  /// Links a dataset to BigQuery in a given project for a given location.
  func linkDataset(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<LinkDatasetResponse>

  /// Unlinks a dataset from BigQuery in a given project
  /// for a given location.
  ///
  /// @Snippet(path: "StorageInsights_UnlinkDataset")
  func unlinkDataset(request: UnlinkDatasetRequest) async throws -> GoogleLongrunning.Operation

  /// Unlinks a dataset from BigQuery in a given project
  /// for a given location.
  func unlinkDataset(withPolling: UnlinkDatasetRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>

  /// Unlinks a dataset from BigQuery in a given project
  /// for a given location.
  func unlinkDataset(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void>

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "StorageInsights_ListLocations")
  func listLocations(request: ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse

  /// Lists information about the supported locations for this service.
  func listLocations(
    byItem: ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

  /// Gets information about a location.
  ///
  /// @Snippet(path: "StorageInsights_GetLocation")
  func getLocation(request: GetLocationRequest) async throws -> GoogleCloudLocation.Location

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "StorageInsights_ListOperations")
  func listOperations(request: ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  func listOperations(
    byItem: ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "StorageInsights_GetOperation")
  func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongrunning.Operation

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "StorageInsights_DeleteOperation")
  func deleteOperation(request: DeleteOperationRequest) async throws

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  func deleteOperation(
    name: Swift.String,
  ) async throws

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "StorageInsights_CancelOperation")
  func cancelOperation(request: CancelOperationRequest) async throws

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  func cancelOperation(
    name: Swift.String,
  ) async throws

  /// Lists ReportConfigs in a given project and location.
  ///
  /// @Snippet(path: "StorageInsights_ListReportConfigs")
  func listReportConfigs(
    request: ListReportConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageinsightsV1.ListReportConfigsResponse

  /// Lists ReportConfigs in a given project and location.
  func listReportConfigs(
    byItem: ListReportConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ReportConfig, Swift.Error>

  /// Gets details of a single ReportConfig.
  ///
  /// @Snippet(path: "StorageInsights_GetReportConfig")
  func getReportConfig(
    request: GetReportConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageinsightsV1.ReportConfig

  /// Creates a new ReportConfig in a given project and location.
  ///
  /// @Snippet(path: "StorageInsights_CreateReportConfig")
  func createReportConfig(
    request: CreateReportConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageinsightsV1.ReportConfig

  /// Updates the parameters of a single ReportConfig.
  ///
  /// @Snippet(path: "StorageInsights_UpdateReportConfig")
  func updateReportConfig(
    request: UpdateReportConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageinsightsV1.ReportConfig

  /// Deletes a single ReportConfig.
  ///
  /// @Snippet(path: "StorageInsights_DeleteReportConfig")
  func deleteReportConfig(
    request: DeleteReportConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws

  /// Lists ReportDetails in a given project and location.
  ///
  /// @Snippet(path: "StorageInsights_ListReportDetails")
  func listReportDetails(
    request: ListReportDetailsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageinsightsV1.ListReportDetailsResponse

  /// Lists ReportDetails in a given project and location.
  func listReportDetails(
    byItem: ListReportDetailsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ReportDetail, Swift.Error>

  /// Gets details of a single ReportDetail.
  ///
  /// @Snippet(path: "StorageInsights_GetReportDetail")
  func getReportDetail(
    request: GetReportDetailRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageinsightsV1.ReportDetail

  /// Lists the dataset configurations in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_ListDatasetConfigs")
  func listDatasetConfigs(
    request: ListDatasetConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageinsightsV1.ListDatasetConfigsResponse

  /// Lists the dataset configurations in a given project for a given location.
  func listDatasetConfigs(
    byItem: ListDatasetConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<DatasetConfig, Swift.Error>

  /// Gets the dataset configuration in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_GetDatasetConfig")
  func getDatasetConfig(
    request: GetDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageinsightsV1.DatasetConfig

  /// Creates a dataset configuration in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_CreateDatasetConfig")
  func createDatasetConfig(
    request: CreateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Creates a dataset configuration in a given project for a given location.
  func createDatasetConfig(
    withPolling: CreateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<DatasetConfig>

  /// Updates a dataset configuration in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_UpdateDatasetConfig")
  func updateDatasetConfig(
    request: UpdateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Updates a dataset configuration in a given project for a given location.
  func updateDatasetConfig(
    withPolling: UpdateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<DatasetConfig>

  /// Deletes a dataset configuration in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_DeleteDatasetConfig")
  func deleteDatasetConfig(
    request: DeleteDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Deletes a dataset configuration in a given project for a given location.
  func deleteDatasetConfig(
    withPolling: DeleteDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void>

  /// Links a dataset to BigQuery in a given project for a given location.
  ///
  /// @Snippet(path: "StorageInsights_LinkDataset")
  func linkDataset(
    request: LinkDatasetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Links a dataset to BigQuery in a given project for a given location.
  func linkDataset(
    withPolling: LinkDatasetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<LinkDatasetResponse>

  /// Unlinks a dataset from BigQuery in a given project
  /// for a given location.
  ///
  /// @Snippet(path: "StorageInsights_UnlinkDataset")
  func unlinkDataset(
    request: UnlinkDatasetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Unlinks a dataset from BigQuery in a given project
  /// for a given location.
  func unlinkDataset(
    withPolling: UnlinkDatasetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void>

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "StorageInsights_ListLocations")
  func listLocations(
    request: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse

  /// Lists information about the supported locations for this service.
  func listLocations(
    byItem: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

  /// Gets information about a location.
  ///
  /// @Snippet(path: "StorageInsights_GetLocation")
  func getLocation(
    request: GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "StorageInsights_ListOperations")
  func listOperations(
    request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  func listOperations(
    byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "StorageInsights_GetOperation")
  func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "StorageInsights_DeleteOperation")
  func deleteOperation(
    request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "StorageInsights_CancelOperation")
  func cancelOperation(
    request: CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws
}

extension Clients {
  /// The recommended implementation for ``StorageInsights``.
  public class StorageInsightsClient: StorageInsights {
    let inner: any StorageInsightsStub

    /// Creates a new `StorageInsightsClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      var inner: any StorageInsightsStub = try StorageInsightsTransport(options)
      inner = StorageInsightsRetry(inner, options: options)
      if let logger = options.logger {
        inner = StorageInsightsLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// See `StorageInsights.listReportConfigs`
    public func listReportConfigs(
      request: ListReportConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageinsightsV1.ListReportConfigsResponse {
      try await self.inner.listReportConfigs(request: request, options: options)
    }

    /// Lists ReportConfigs in a given project and location.
    public func listReportConfigs(
      byItem: ListReportConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ReportConfig, Swift.Error> {
      let listRpc = {
        (token: String) async throws -> GoogleCloudStorageinsightsV1.ListReportConfigsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listReportConfigs(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `StorageInsights.getReportConfig`
    public func getReportConfig(
      request: GetReportConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageinsightsV1.ReportConfig {
      try await self.inner.getReportConfig(request: request, options: options)
    }

    /// See `StorageInsights.createReportConfig`
    public func createReportConfig(
      request: CreateReportConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageinsightsV1.ReportConfig {
      try await self.inner.createReportConfig(request: request, options: options)
    }

    /// See `StorageInsights.updateReportConfig`
    public func updateReportConfig(
      request: UpdateReportConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageinsightsV1.ReportConfig {
      try await self.inner.updateReportConfig(request: request, options: options)
    }

    /// See `StorageInsights.deleteReportConfig`
    public func deleteReportConfig(
      request: DeleteReportConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.deleteReportConfig(request: request, options: options)
    }

    /// See `StorageInsights.listReportDetails`
    public func listReportDetails(
      request: ListReportDetailsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageinsightsV1.ListReportDetailsResponse {
      try await self.inner.listReportDetails(request: request, options: options)
    }

    /// Lists ReportDetails in a given project and location.
    public func listReportDetails(
      byItem: ListReportDetailsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ReportDetail, Swift.Error> {
      let listRpc = {
        (token: String) async throws -> GoogleCloudStorageinsightsV1.ListReportDetailsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listReportDetails(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `StorageInsights.getReportDetail`
    public func getReportDetail(
      request: GetReportDetailRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageinsightsV1.ReportDetail {
      try await self.inner.getReportDetail(request: request, options: options)
    }

    /// See `StorageInsights.listDatasetConfigs`
    public func listDatasetConfigs(
      request: ListDatasetConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageinsightsV1.ListDatasetConfigsResponse {
      try await self.inner.listDatasetConfigs(request: request, options: options)
    }

    /// Lists the dataset configurations in a given project for a given location.
    public func listDatasetConfigs(
      byItem: ListDatasetConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<DatasetConfig, Swift.Error> {
      let listRpc = {
        (token: String) async throws -> GoogleCloudStorageinsightsV1.ListDatasetConfigsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listDatasetConfigs(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `StorageInsights.getDatasetConfig`
    public func getDatasetConfig(
      request: GetDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudStorageinsightsV1.DatasetConfig {
      try await self.inner.getDatasetConfig(request: request, options: options)
    }

    /// See `StorageInsights.createDatasetConfig`
    public func createDatasetConfig(
      request: CreateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.createDatasetConfig(request: request, options: options)
    }

    /// Creates a dataset configuration in a given project for a given location.
    public func createDatasetConfig(
      withPolling: CreateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<DatasetConfig> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<DatasetConfig>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try DatasetConfig(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.createDatasetConfig(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<DatasetConfig>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `StorageInsights.updateDatasetConfig`
    public func updateDatasetConfig(
      request: UpdateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.updateDatasetConfig(request: request, options: options)
    }

    /// Updates a dataset configuration in a given project for a given location.
    public func updateDatasetConfig(
      withPolling: UpdateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<DatasetConfig> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<DatasetConfig>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try DatasetConfig(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.updateDatasetConfig(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<DatasetConfig>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `StorageInsights.deleteDatasetConfig`
    public func deleteDatasetConfig(
      request: DeleteDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.deleteDatasetConfig(request: request, options: options)
    }

    /// Deletes a dataset configuration in a given project for a given location.
    public func deleteDatasetConfig(
      withPolling: DeleteDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<Void>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response:
          return .init(done: true, result: .success(()))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.deleteDatasetConfig(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `StorageInsights.linkDataset`
    public func linkDataset(
      request: LinkDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.linkDataset(request: request, options: options)
    }

    /// Links a dataset to BigQuery in a given project for a given location.
    public func linkDataset(
      withPolling: LinkDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<LinkDatasetResponse> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<LinkDatasetResponse>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try LinkDatasetResponse(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.linkDataset(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        () async throws -> GoogleCloudGax._PollableOperationImpl<LinkDatasetResponse>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `StorageInsights.unlinkDataset`
    public func unlinkDataset(
      request: UnlinkDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.unlinkDataset(request: request, options: options)
    }

    /// Unlinks a dataset from BigQuery in a given project
    /// for a given location.
    public func unlinkDataset(
      withPolling: UnlinkDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<Void>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response:
          return .init(done: true, result: .success(()))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.unlinkDataset(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `StorageInsights.listLocations`
    public func listLocations(
      request: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self.inner.listLocations(request: request, options: options)
    }

    /// Lists information about the supported locations for this service.
    public func listLocations(
      byItem: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
      let listRpc = { (token: String) async throws -> GoogleCloudLocation.ListLocationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listLocations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `StorageInsights.getLocation`
    public func getLocation(
      request: GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self.inner.getLocation(request: request, options: options)
    }

    /// See `StorageInsights.listOperations`
    public func listOperations(
      request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self.inner.listOperations(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
    public func listOperations(
      byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
      let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listOperations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `StorageInsights.getOperation`
    public func getOperation(
      request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }

    /// See `StorageInsights.deleteOperation`
    public func deleteOperation(
      request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.deleteOperation(request: request, options: options)
    }

    /// See `StorageInsights.cancelOperation`
    public func cancelOperation(
      request: CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.cancelOperation(request: request, options: options)
    }
  }
}

// Default implementations
extension StorageInsights {
  public func listReportConfigs(request: ListReportConfigsRequest) async throws
    -> GoogleCloudStorageinsightsV1.ListReportConfigsResponse
  {
    try await self.listReportConfigs(request: request, options: .init())
  }

  public func listReportConfigs(
    request: ListReportConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageinsightsV1.ListReportConfigsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listReportConfigs(
    byItem: ListReportConfigsRequest
  ) throws -> any AsyncSequence<ReportConfig, Swift.Error> {
    try self.listReportConfigs(byItem: byItem, options: .init())
  }

  public func listReportConfigs(
    byItem: ListReportConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ReportConfig, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleCloudStorageinsightsV1.ListReportConfigsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listReportConfigs(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ReportConfig, Swift.Error> {
    let request = ListReportConfigsRequest().with {
      $0.parent = parent
    }
    return try self.listReportConfigs(byItem: request)
  }

  public func getReportConfig(request: GetReportConfigRequest) async throws
    -> GoogleCloudStorageinsightsV1.ReportConfig
  {
    try await self.getReportConfig(request: request, options: .init())
  }

  public func getReportConfig(
    request: GetReportConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageinsightsV1.ReportConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getReportConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudStorageinsightsV1.ReportConfig {
    let request = GetReportConfigRequest().with {
      $0.name = name
    }
    return try await self.getReportConfig(request: request)
  }

  public func createReportConfig(request: CreateReportConfigRequest) async throws
    -> GoogleCloudStorageinsightsV1.ReportConfig
  {
    try await self.createReportConfig(request: request, options: .init())
  }

  public func createReportConfig(
    request: CreateReportConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageinsightsV1.ReportConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createReportConfig(
    parent: Swift.String,
    reportConfig: ReportConfig?,
  ) async throws -> GoogleCloudStorageinsightsV1.ReportConfig {
    let request = CreateReportConfigRequest().with {
      $0.parent = parent
      $0.reportConfig = reportConfig
    }
    return try await self.createReportConfig(request: request)
  }

  public func updateReportConfig(request: UpdateReportConfigRequest) async throws
    -> GoogleCloudStorageinsightsV1.ReportConfig
  {
    try await self.updateReportConfig(request: request, options: .init())
  }

  public func updateReportConfig(
    request: UpdateReportConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageinsightsV1.ReportConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateReportConfig(
    reportConfig: ReportConfig?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleCloudStorageinsightsV1.ReportConfig {
    let request = UpdateReportConfigRequest().with {
      $0.reportConfig = reportConfig
      $0.updateMask = updateMask
    }
    return try await self.updateReportConfig(request: request)
  }

  public func deleteReportConfig(request: DeleteReportConfigRequest) async throws {
    try await self.deleteReportConfig(request: request, options: .init())
  }

  public func deleteReportConfig(
    request: DeleteReportConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteReportConfig(
    name: Swift.String,
  ) async throws {
    let request = DeleteReportConfigRequest().with {
      $0.name = name
    }
    try await self.deleteReportConfig(request: request)
  }

  public func listReportDetails(request: ListReportDetailsRequest) async throws
    -> GoogleCloudStorageinsightsV1.ListReportDetailsResponse
  {
    try await self.listReportDetails(request: request, options: .init())
  }

  public func listReportDetails(
    request: ListReportDetailsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageinsightsV1.ListReportDetailsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listReportDetails(
    byItem: ListReportDetailsRequest
  ) throws -> any AsyncSequence<ReportDetail, Swift.Error> {
    try self.listReportDetails(byItem: byItem, options: .init())
  }

  public func listReportDetails(
    byItem: ListReportDetailsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ReportDetail, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleCloudStorageinsightsV1.ListReportDetailsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listReportDetails(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ReportDetail, Swift.Error> {
    let request = ListReportDetailsRequest().with {
      $0.parent = parent
    }
    return try self.listReportDetails(byItem: request)
  }

  public func getReportDetail(request: GetReportDetailRequest) async throws
    -> GoogleCloudStorageinsightsV1.ReportDetail
  {
    try await self.getReportDetail(request: request, options: .init())
  }

  public func getReportDetail(
    request: GetReportDetailRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageinsightsV1.ReportDetail {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getReportDetail(
    name: Swift.String,
  ) async throws -> GoogleCloudStorageinsightsV1.ReportDetail {
    let request = GetReportDetailRequest().with {
      $0.name = name
    }
    return try await self.getReportDetail(request: request)
  }

  public func listDatasetConfigs(request: ListDatasetConfigsRequest) async throws
    -> GoogleCloudStorageinsightsV1.ListDatasetConfigsResponse
  {
    try await self.listDatasetConfigs(request: request, options: .init())
  }

  public func listDatasetConfigs(
    request: ListDatasetConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageinsightsV1.ListDatasetConfigsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listDatasetConfigs(
    byItem: ListDatasetConfigsRequest
  ) throws -> any AsyncSequence<DatasetConfig, Swift.Error> {
    try self.listDatasetConfigs(byItem: byItem, options: .init())
  }

  public func listDatasetConfigs(
    byItem: ListDatasetConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<DatasetConfig, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleCloudStorageinsightsV1.ListDatasetConfigsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listDatasetConfigs(
    parent: Swift.String,
  ) throws -> any AsyncSequence<DatasetConfig, Swift.Error> {
    let request = ListDatasetConfigsRequest().with {
      $0.parent = parent
    }
    return try self.listDatasetConfigs(byItem: request)
  }

  public func getDatasetConfig(request: GetDatasetConfigRequest) async throws
    -> GoogleCloudStorageinsightsV1.DatasetConfig
  {
    try await self.getDatasetConfig(request: request, options: .init())
  }

  public func getDatasetConfig(
    request: GetDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudStorageinsightsV1.DatasetConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getDatasetConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudStorageinsightsV1.DatasetConfig {
    let request = GetDatasetConfigRequest().with {
      $0.name = name
    }
    return try await self.getDatasetConfig(request: request)
  }

  public func createDatasetConfig(request: CreateDatasetConfigRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.createDatasetConfig(request: request, options: .init())
  }

  public func createDatasetConfig(
    request: CreateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createDatasetConfig(withPolling: CreateDatasetConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<DatasetConfig>
  {
    try await self.createDatasetConfig(withPolling: withPolling, options: .init())
  }

  public func createDatasetConfig(
    withPolling: CreateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<DatasetConfig> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<DatasetConfig>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createDatasetConfig(
    parent: Swift.String,
    datasetConfig: DatasetConfig?,
    datasetConfigId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<DatasetConfig> {
    let request = CreateDatasetConfigRequest().with {
      $0.parent = parent
      $0.datasetConfig = datasetConfig
      $0.datasetConfigId = datasetConfigId
    }
    return try await self.createDatasetConfig(withPolling: request)
  }

  public func updateDatasetConfig(request: UpdateDatasetConfigRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.updateDatasetConfig(request: request, options: .init())
  }

  public func updateDatasetConfig(
    request: UpdateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateDatasetConfig(withPolling: UpdateDatasetConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<DatasetConfig>
  {
    try await self.updateDatasetConfig(withPolling: withPolling, options: .init())
  }

  public func updateDatasetConfig(
    withPolling: UpdateDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<DatasetConfig> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<DatasetConfig>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateDatasetConfig(
    datasetConfig: DatasetConfig?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<DatasetConfig> {
    let request = UpdateDatasetConfigRequest().with {
      $0.datasetConfig = datasetConfig
      $0.updateMask = updateMask
    }
    return try await self.updateDatasetConfig(withPolling: request)
  }

  public func deleteDatasetConfig(request: DeleteDatasetConfigRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.deleteDatasetConfig(request: request, options: .init())
  }

  public func deleteDatasetConfig(
    request: DeleteDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteDatasetConfig(withPolling: DeleteDatasetConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Void>
  {
    try await self.deleteDatasetConfig(withPolling: withPolling, options: .init())
  }

  public func deleteDatasetConfig(
    withPolling: DeleteDatasetConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteDatasetConfig(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteDatasetConfigRequest().with {
      $0.name = name
    }
    return try await self.deleteDatasetConfig(withPolling: request)
  }

  public func linkDataset(request: LinkDatasetRequest) async throws -> GoogleLongrunning.Operation {
    try await self.linkDataset(request: request, options: .init())
  }

  public func linkDataset(
    request: LinkDatasetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func linkDataset(withPolling: LinkDatasetRequest) async throws -> any GoogleCloudGax
    .PollableOperation<LinkDatasetResponse>
  {
    try await self.linkDataset(withPolling: withPolling, options: .init())
  }

  public func linkDataset(
    withPolling: LinkDatasetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<LinkDatasetResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<LinkDatasetResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func linkDataset(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<LinkDatasetResponse> {
    let request = LinkDatasetRequest().with {
      $0.name = name
    }
    return try await self.linkDataset(withPolling: request)
  }

  public func unlinkDataset(request: UnlinkDatasetRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.unlinkDataset(request: request, options: .init())
  }

  public func unlinkDataset(
    request: UnlinkDatasetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func unlinkDataset(withPolling: UnlinkDatasetRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>
  {
    try await self.unlinkDataset(withPolling: withPolling, options: .init())
  }

  public func unlinkDataset(
    withPolling: UnlinkDatasetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func unlinkDataset(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = UnlinkDatasetRequest().with {
      $0.name = name
    }
    return try await self.unlinkDataset(withPolling: request)
  }

  public func listLocations(request: ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GetLocationRequest) async throws -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let request = ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongrunning.Operation {
    let request = GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
