// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [`UpdateDatasetConfig`][google.cloud.storageinsights.v1.StorageInsights.UpdateDatasetConfig]
///
/// [google.cloud.storageinsights.v1.StorageInsights.UpdateDatasetConfig]: <doc:StorageInsights/updateDatasetConfig(request:)>
public struct UpdateDatasetConfigRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Field mask is used to specify the fields to be overwritten in the
  /// `DatasetConfig` resource by the update.
  /// The fields specified in the `update_mask` are relative to the resource, not
  /// the full request. A field is overwritten if it is in the mask. If the
  /// user does not provide a mask then it returns an "Invalid Argument" error.
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// Required. The resource being updated
  public var datasetConfig: DatasetConfig? = nil

  /// Optional. A unique identifier for your request.
  /// Specify the request ID if you need to retry the request.
  /// If you retry the request with the same ID within 60 minutes, the server
  /// ignores the request if it has already completed the original request.
  ///
  /// For example, if your initial request times out and you retry the request
  /// using the same request ID, the server recognizes the original request and
  /// does not process the new request.
  ///
  /// The request ID must be a valid UUID and cannot be a zero UUID
  /// (00000000-0000-0000-0000-000000000000).
  public var requestId: Swift.String = Swift.String()

  /// Initialize a new instance of `UpdateDatasetConfigRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateDatasetConfigRequest().with { $0.updateMask = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.storageinsights.v1.UpdateDatasetConfigRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
